# -*- coding: utf-8 -*-
"""196 final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WCkWVkLYBEQl_2B6sieGJMa9IfQoqELX
"""

#Josh Weiss
#Coach D
#BSAD 196 Final
#This code will gather information on 20 stocks and analyze their data.

#install yahoo finance

# Import yfinance
import yfinance as yf


# ticker = input("Please enter the ticker symbol: ").upper()


# Get the data for the stock Apple by specifying the stock ticker, start date, and end date
data10y = yf.download('AAPL AIR BP BUD CRM CSCO DAL DFS DRI EADSY IHG LUV MFA MTN RCL SWBI SYY USB USPH XOM', start= '2010-12-31', end= '2020-12-31')
data5y = yf.download('AAPL AIR BP BUD CRM CSCO DAL DFS DRI EADSY IHG LUV MFA MTN RCL SWBI SYY USB USPH XOM',  start= '2015-12-31', end= '2020-12-31')
data3y = yf.download('AAPL AIR BP BUD CRM CSCO DAL DFS DRI EADSY IHG LUV MFA MTN RCL SWBI SYY USB USPH XOM', start= '2017-12-31', end= '2020-12-31')
data1y = yf.download('AAPL AIR BP BUD CRM CSCO DAL DFS DRI EADSY IHG LUV MFA MTN RCL SWBI SYY USB USPH XOM', start= '2019-12-31', end= '2020-12-31')

#save the stock data as csv files
data10y.to_csv('stocks10y.csv')
data5y.to_csv('stocks5y.csv')
data3y.to_csv('stocks3y.csv')
data1y.to_csv('stocks1y.csv')


#find % change etween all days over 10 years

closing = data10y ['Close']
dr= closing.pct_change()
dr.to_csv('closingchange10y.csv')

#done
#graph of 10k invested in each stock over 10 years


#import matplotlib
import matplotlib.pyplot as plt


tickerList = ['AAPL', 'AIR', 'BP', 'BUD', 'CRM', 'CSCO', 'DAL', 'DFS', 'DRI', 'EADSY', 'IHG', 'LUV', 'MFA', 'MTN', 'RCL', 'SWBI', 'SYY', 'USB', 'USPH', 'XOM']

for ticker in tickerList:
    stock = dr[ticker]

    valueList = []
    dayCountList = []

    value = 10000
    count = 0
    for pctChange in stock:
        if count == 0:
            print("SKIPPING NAN ROW")
            count = count + 1
        else:
            value = value + (value * pctChange)
            dayCountList.append(count)
            valueList.append(value)
            count = count + 1

    plt.plot(dayCountList, valueList)
    plt.show()

    print("Final Value After 10 Years: " + str(value) + " For the stock: " + ticker)

#compound annual growth rate
#make a csv of closing prices 10 y
tenyear = data10y ['Close']
tenyear.to_csv('tenyear.csv')

first10= tenyear.iloc[0]
last10= tenyear.iloc[-1]
cagr10= (last10/first10)**(1/10)-1


#make acsv of closing prices 5y
fiveyear = data5y ['Close']
fiveyear.to_csv('fiveyear.csv')

first5= fiveyear.iloc[0]
last5= fiveyear.iloc[-1]
cagr5= (last5/first5)**(1/10)-1

#make a csv of closing prices 3y
threeyear= data3y ['Close']
threeyear.to_csv('threeyear.csv')

first3= threeyear.iloc[0]
last3= threeyear.iloc[-1]
cagr3= (last3/first3)**(1/10)-1

#make a csv of closing prices 1 y
oneyear = data1y ['Close']
oneyear.to_csv('oneyear.csv')

first1= oneyear.iloc[1]
last1= oneyear.iloc[-1]
cagr1= (last1/first1)**(1/10)-1

print(first1)
print(last1)

#output all cagrs to their own csv then on excel will comine into a table
cagr10.to_csv('cagr10.csv')
cagr5.to_csv('cagr5.csv')
cagr3.to_csv('cagr3.csv')
cagr1.to_csv('cagr1.csv')

#done

#covariance matrix

#referencing ealier when find % change
cov_matrix = dr.cov()
cov_matrix = (dr.cov())*250
print (cov_matrix)

cov_matrix.to_csv('cov_matrix.csv')